repos:
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        args: [--ignore-missing-imports]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
    -   id: ruff
        args: [--ignore=E501]
