[project]
name = "homework-fastapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.119.0",
    "sacremoses>=0.1.1",
    "torch>=2.9.0",
    "transformers[sentencepiece]>=4.57.1",
    "uvicorn>=0.38.0",
]
